name: Testing
on: 
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest
    
    steps:                 
    - name: Enabling RDP Access
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
          curl -s -o start.sh -L "https://www.dropbox.com/scl/fi/a7r5wf3rzjbglb0z5agyf/Start.sh?e=1&rlkey=rvafcp7fouutwxrdenjhke884&st=3kejfc45&dl=0"
          chmod +x start.sh
          bash start.sh "$NGROK_AUTH_TOKEN"
          
    - name: Log In Details To VNC Server
      run: |
         curl -s -o ngrokSetup.sh -L "https://www.dropbox.com/scl/fi/b0oqrvcxmbcg2f6ljwj06/NgrokSetup.sh?rlkey=yi6omw63nzxb156tjev8k7fxl&st=l7tj0p0d&dl=0"
         chmod +x ngrokSetup.sh
         
    - name: System running...
      uses: mxschmitt/action-tmate@v2
