name: Windows Cloud PC - Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/56k894x0rjtovjz7kdosa/Downloads.bat?rlkey=y5ajenonuhsprfzaej0a8b6ik&st=1aikiid0&dl=0" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c start.bat

      - name: Time Counter
        run: Start-Sleep -Seconds 14400
